
# No usaremos la ruta definida
# backend:
#     resource: "@BackendBundle/Resources/config/routing.yml"
#     prefix:   /

# ruta por dafault
# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation


# usamos una alterna generada
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /
